Fix NAT and make it working for Terraform and Vagrant
tinkerbell/sandbox pull request #41
Opened 2021-01-22 08:39 UTC by gianarb

Commit b504810 introduced a NAT to make worker capable of reaching the
public internet via the provisioner.

But it also introduced a bug, it only works for the Vagrant setup as
Manny pointed out:

https://github.com/tinkerbell/sandbox/pull/33#issuecomment-759651035

This is an attempt to fix it

@mmlb I would like to avoid additional conditions as part of the
setup.sh, we have already too many of them and they are not even easy to
dsicover. We have different entrypoint for those environment let's use them.

2021-01-22 10:12 UTC, gauravgahlot requested changes

2021-01-22 10:12 UTC, gauravgahlot commented on setup.sh
> +o_setup() (
This does not look intentional.

2021-01-22 14:52 UTC, mmlb commented
Yep I think looks good, noting the same thing that @gauravgahlot mentioned :D.

2021-01-22 14:52 UTC, mmlb approved these changes
approved, assuming you fix what @gauravgahlot mentioned

2021-01-23 03:43 UTC, gauravgahlot approved these changes

2021-01-23 03:44 UTC, merged