Add support for a nat-less libvirt deployment and multiple workers
tinkerbell/sandbox pull request #65
Opened 2021-03-17 20:35 UTC by detiber

## Description

Allows for deploying the vagrant/libvirt setup without NAT and with multiple workers, which enables testing with cluster-api-provider-tink

## Why is this needed

Helps with testing CAPT

## How Has This Been Tested?

Currently testing at the moment, but all testing will consist of manual testing with vagrant/libvirt

## How are existing users impacted? What migration steps/scripts do we need?

This could affect existing vagrant/libvirt users if they have an existing worker running when they update, not sure if there is a good way to avoid that, though.

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [ ] provided instructions on how to upgrade

2021-03-18 07:47 UTC, gauravgahlot approved these changes

2021-03-18 09:39 UTC, gianarb approved these changes

2021-03-18 09:54 UTC, gianarb requested changes
Hello! Great work this change breaks our CI/CD because it changes the name of the worker from `worker` to `worker-1`. Can you update the test suite as well? I am not sure if somewhere in the documentation is mentioned `worker` instead of `worker-1`, if so we have to update documentation as well

2021-03-18 13:54 UTC, detiber commented
> Hello! Great work this change breaks our CI/CD because it changes the name of the worker from `worker` to `worker-1`. Can you update the test suite as well? I am not sure if somewhere in the documentation is mentioned `worker` instead of `worker-1`, if so we have to update documentation as well

Updated to avoid the renaming of the first worker, the first worker will remain named `worker` and subsequent workers are named `worker<n>`

2021-03-19 07:47 UTC, gianarb approved these changes

2021-03-19 07:47 UTC, gianarb approved these changes

2021-03-19 07:55 UTC, merged